packages: []

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@ooopsstudio/analytics-consent-astro@0.3.0'
  - '@ooopsstudio/analytics-consent@0.3.0'
  - '@ooopsstudio/cms-api@0.2.0'
  - '@ooopsstudio/cms-astro@0.2.1'
  - '@ooopsstudio/cms-cloudflare@0.2.1'

overrides:
  esbuild: ^0.28.1
